### ISSUE TITLE
Logging issues with tracker interface

### ISSUE THREAD

**Issue by sridhargaddam** [submariner-io/admiral#373]
subctl diagnose (along with many other APIs in subctl) use the tracker interface to display status messages.
While validating some deployments, the following logs were noticed.

```
 ✗ Non-Globalnet deployment detected - checking if cluster CIDRs overlap 
 ✗ CIDR ["172.30.0.0/16" "sgaddam-aws-spoke2" "sgaddam-aws-spoke1" ["172.30.0.0/16" "10.128.0.0/14"]] in cluster %!q(MISSING) overlaps with cluster %!q(MISSING) (CIDRs: %!v(MISSING))
 ✗ CIDR ["10.128.0.0/14" "sgaddam-aws-spoke2" "sgaddam-aws-spoke1" ["172.30.0.0/16" "10.128.0.0/14"]] in cluster %!q(MISSING) overlaps with cluster %!q(MISSING) (CIDRs: %!v(MISSING))
```

**Comment by nyechiel** [comment]
@sridhargaddam should this be backported for inclusion with rc1?

**Comment by tpantelis** [comment]
> @sridhargaddam should this be backported for inclusion with rc1?

it is: https://github.com/submariner-io/admiral/pull/375
