### ISSUE TITLE
Increase Admiral unit test coverage

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/admiral#485]
We now have easy insight into unit test coverage via SonarCloud. The current UT coverage for the submariner-io/admiral repo is 52.8%. We should strive to improve UT coverage, ideally initially up to at least 70%.

https://sonarcloud.io/summary/overall?id=submariner-io_admiral
https://sonarcloud.io/component_measures?id=submariner-io_admiral&metric=coverage&view=list

**Comment by tpantelis** [comment]
With recent changes, code coverage is now at [63%](https://sonarcloud.io/component_measures?metric=coverage&view=list&id=submariner-io_admiral).

**Comment by tpantelis** [comment]
Code coverage is now at 78%. I plan to increase it more over time but the objective  for this issue has been reached.
